# Generated by Django 4.1 on 2023-05-28 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestaurantApp', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='RestaurantApp.menu')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
