# Generated by Django 4.1 on 2023-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0005_comensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
