# Generated by Django 4.1.6 on 2023-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0006_menu_imagen_helado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
